import { StyleSheet } from 'react-native';

/**
 * Stylesheet for LiveStageScreen.
 * Pure OLED dark theme (#000000) optimized for stage environments, music stands,
 * metronome visual indicators, and floating bottom auto-scroll controls.
 */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#121212',
    borderBottomWidth: 1,
    borderBottomColor: '#262626',
  },
  exitIconBtn: {
    padding: 4,
  },
  centerSongInfo: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 8,
  },
  songTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    gap: 8,
  },
  songPagination: {
    color: '#9E9E9E',
    fontSize: 12,
  },
  metronomeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metronomeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#424242',
    marginRight: 4,
  },
  metronomeDotActive: {
    backgroundColor: '#00E676',
    transform: [{ scale: 1.3 }],
  },
  bpmText: {
    color: '#00E676',
    fontSize: 12,
    fontWeight: '600',
  },
  timeSigText: {
    color: '#9E9E9E',
    fontSize: 12,
  },
  navButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  navBtn: {
    backgroundColor: '#262626',
    width: 32,
    height: 32,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navBtnDisabled: {
    opacity: 0.3,
  },
  controlSubBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1A1A1A',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#262626',
  },
  keyControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  subBarLabel: {
    color: '#BDBDBD',
    fontSize: 13,
    fontWeight: '600',
    marginRight: 6,
  },
  stepperBtn: {
    backgroundColor: '#2E2E2E',
    width: 28,
    height: 28,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 3,
  },
  keyBadge: {
    backgroundColor: '#3E2723',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
  },
  keyBadgeText: {
    color: '#FFB74D',
    fontSize: 13,
    fontWeight: '700',
  },
  resetBtn: {
    backgroundColor: '#2E2E2E',
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 4,
    marginLeft: 4,
  },
  resetBtnText: {
    color: '#29B6F6',
    fontSize: 11,
    fontWeight: '700',
  },
  fontControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  fontBtn: {
    backgroundColor: '#2E2E2E',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 5,
  },
  fontBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  emptyLine: {
    height: 18,
  },
  sectionBadge: {
    backgroundColor: '#263238',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    marginTop: 14,
    marginBottom: 6,
  },
  sectionBadgeText: {
    color: '#80CBC4',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  lyricLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  chordWordItem: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  chordText: {
    color: '#FF9800',
    fontWeight: '800',
    fontFamily: 'monospace',
    marginBottom: 2,
  },
  chordSpacer: {
    lineHeight: 18,
  },
  lyricText: {
    color: '#FFFFFF',
    lineHeight: 28,
  },
  floatingDock: {
    position: 'absolute',
    bottom: 24,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 30, 30, 0.94)',
    borderRadius: 30,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 12,
    borderWidth: 1,
    borderColor: '#333333',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  dockPlayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E65100',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  dockPlayBtnActive: {
    backgroundColor: '#C2185B',
  },
  dockPlayText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  speedControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  speedBtn: {
    backgroundColor: '#3E3E3E',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  speedText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 4,
  },
  emptyText: {
    color: '#FFFFFF',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
  },
  exitButton: {
    alignSelf: 'center',
    marginTop: 20,
    backgroundColor: '#E65100',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  exitButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
});
